###
GET http://localhost:8080/live/categoryInfos

###
GET http://localhost:8080/bilibili/category/roomInfos?parentAreaId=9&areaId=744&sort_type=online&page=2

###
GET http://localhost:8080/bilibili/search?keyword=lol&page=1

###
GET http://localhost:8080/bilibili/realUrl/10112

###
GET http://localhost:8080/douyu/category/roomInfos?categoryLevelAndId=2_1&page=1

###
GET http://localhost:8080/douyu/search?keyword=lol&page=1

###
GET http://localhost:8080/douyu/realUrl/288016